name: CI

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Resolve
      run: swift package resolve
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
    - name: Build fixtures
      run: ./build_specs.sh